In [119]:
import numpy as np
import sys

In [120]:
nQueens = 8
STOP_CTR = 28
MUTATE = 0.000001
MUTATE_FLAG = True
MAX_ITER = 100000
POPULATION = None

class BoardPosition:
    def __init__(self):
        self.sequence = None
        self.fitness = None
        self.survival = None
    def setSequence(self, val):
        self.sequence = val
    def setFitness(self, fitness):
        self.fitness = fitness
    def setSurvival(self, val):
        self.survival = val
    def getAttr(self):
        return {'sequence':sequence, 'fitness':fitness, 'survival':survival}


In [121]:

def fitness(chromosome = None):
    """    
    max fitness = 7 + 6 + 5 + 4 + 3 + 2 + 1 = 28
    for each non attack queens placed
    hence fitness val returned will be 28 - <number of clashes>
    """
    clashes = 0;
    row_col_clashes = abs(len(chromosome) - len(np.unique(chromosome)))
    clashes += row_col_clashes

    # calculate diagonal clashes
    for i in range(len(chromosome)):
        for j in range(i,len(chromosome)):
            if (i != j):
                dx = abs(i-j)
                dy = abs(chromosome[i] - chromosome[j])
                if(dx == dy):
                    clashes += 1


    return 28 - clashes

In [122]:
def generateChromosome():
    global nQueens
    init_distribution = np.arange(nQueens)
    np.random.shuffle(init_distribution)
    return init_distribution

def generatePopulation(population_size = 100):
    global POPULATION

    POPULATION = population_size

    population = [BoardPosition() for i in range(population_size)]
    for i in range(population_size):
        population[i].setSequence(generateChromosome())
        population[i].setFitness(fitness(population[i].sequence))

    return population

In [123]:
def getParent():
    globals()
    parent1, parent2 = None, None
    
    summation_fitness = np.sum([x.fitness for x in population])
    for each in population:
        each.survival = each.fitness/(summation_fitness*1.0)

    while True:
        parent1_random = np.random.rand()
        parent1_rn = [x for x in population if x.survival <= parent1_random]
        try:
            parent1 = parent1_rn[0]
            break
        except:
            pass

    while True:
        parent2_random = np.random.rand()
        parent2_rn = [x for x in population if x.survival <= parent2_random]
        try:
            t = np.random.randint(len(parent2_rn))
            parent2 = parent2_rn[t]
            if parent2 != parent1:
                break
            else:
                print ("equal parents")
                continue
        except:
            print ("exception")
            continue

    if parent1 is not None and parent2 is not None:
        return parent1, parent2
    else:
        sys.exit(-1)

In [124]:
def reproduce_crossover(parent1, parent2):
    globals()
    n = len(parent1.sequence)
    c = np.random.randint(n, size=1)
    child = BoardPosition()
    child.sequence = []
    child.sequence.extend(parent1.sequence[0:c])
    child.sequence.extend(parent2.sequence[c:])
    child.setFitness(fitness(child.sequence))
    return child

In [125]:
def mutate(child):
    
    if child.survival < MUTATE:
        c = np.random.randint(8)
        child.sequence[c] = np.random.randint(8)
    return child

In [126]:
def GA(iteration):
    #print (" #"*10 ,"Executing Genetic  generation : ", iteration , " #"*10)
    globals()
    newpopulation = []
    for i in range(len(population)):
        parent1, parent2 = getParent()
        child = reproduce_crossover(parent1, parent2)
        if(MUTATE_FLAG):
            child = mutate(child)

        newpopulation.append(child)
    return newpopulation

In [127]:
def stop():
    globals()
    # print (population[0], " printing population[0]")
    fitnessvals = [pos.fitness for pos in population]
    if STOP_CTR in fitnessvals:
        return True
    if MAX_ITER == iteration:
        return True
    return False

In [129]:
population = generatePopulation(1000)

#print ("POPULATION size : ", population)

iteration = 0
while not stop():
    # keep iteratin till  you find the best position
    population = GA(iteration)
    iteration +=1 

#print ("Iteration number : ", iteration)
for each in population:
    if each.fitness == 28:
        print (each.sequence)

[4 2 0 6 1 7 5 3]
[5 1 6 0 2 4 7 3]
[5 3 6 0 7 1 4 2]
[5 2 0 7 4 1 3 6]
[3 6 2 7 1 4 0 5]
